### PR TITLE
Correction of attribute "visible"

### PR DESCRIPTION
**Pull request by freton**

### CODE REVIEW

**Comment by oligus** [comment]
Thank you very much for your PR! We had this problem in #31 but i could not replicate it. Can you give me an example of this?

Thanks again! :-)

**Comment by freton** [comment]
Hello, how are you?
This problem was happening when I added more than one attribute in the annotation of the entity. The getProperty method was not bringing it in, replaced by getProperties and brought all anannotation, that foreach checks if the visible property exists and then applies.
I'm running out of time to do a deeper research on reflection, so it was the quickest way to get this resolved for now.

**Comment by freton** [comment]
Sorry, I closed it !!

**Comment by oligus** [comment]
Hi, sorry for late reply! I'm not getting how to reproduce this bug, for instance if I have a attribute:

```
/**
 * @ORM\Column(name="BillingCountry", type="string", length=40)
 * @JAD\Attribute(readOnly=false, visible=false)
 */
 protected $billingCountry;
```

It wont display `billing-country`and visavi if I set visible to true, it shows.

Can you help me reproduce it so I can understand what is failing? What does your entity look like?

Thanks again!

**Comment by oligus** [comment]
ping @freton, do you have any more on this? I really would like to understand how to reproduce the `visible` bug. Thanks again!

**Comment by freton** [comment]
Hi, sorry for later replay.

/**
 * @var "Entity\BillingCountry"
 *
 * @ORM\Column(name="Entity\BillingCountry", type="string", length=40)
 * @JAD\Attribute(readOnly=false, visible=false)
 */
 protected $billingCountry;

**Comment by oligus** [comment]
I still do not understand how to replicate this behaviour.

**Entity, visible is true:**
screen shot 2018-01-24 at 17 20 57

**Result, billing-country is visible:**
screen_shot_2018-01-24_at_17_21_09

**Entity, visible is false:**
screen shot 2018-01-24 at 17 21 24

**Result, billing-country is not visible:**
screen shot 2018-01-24 at 17 21 33

This is what it looks like for me, what is the difference between your environment and mine? What JAD version are you running?

**Comment by freton** [comment]
Hello, how are you?
Try to use it in the format of the annotation I sent earlier, I think that should be the problem then. Note that in the first line of the annotation there is a "@var type"
I am using the same version as # 31.

**Comment by oligus** [comment]
I'm sorry but I cannot reproduce this even with your annotations. What does the variable `$jadAnnotation` contain when you encounter this error?

**Comment by freton** [comment]
It does not return an error, but returns an empty array

**Comment by oligus** [comment]
See, that's the thing, it doesn't do that for me. Might it be the annotation library, what version of Doctrine are you using?

**Comment by freton** [comment]
hi, Doctrine1.4

**Comment by oligus** [comment]
Ok, that is probably the reason. I will tag up a new version from current master, but after that I will require doctrine 2.x

**Pull request closed without merging**
